spring:
  application:
    name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: msadmin
      password: 12345

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false